# waypoints list
waypoints_list:
    - id: 0
      x: 2000
      y: 2000

    - id: 1
      x: 2140
      y: 2000

    - id: 2
      x: 2140
      y: 2336

    - id: 3
      x: 2000
      y: 2336

    - id: 4
      x: 1860
      y: 2336

    - id: 5
      x: 1860
      y: 2000

    - id: 6
      x: 1860
      y: 1660

    - id: 7
      x: 2000
      y: 1660

    - id: 8
      x: 2140
      y: 1660

    - id: 9
      x: 2140
      y: 2000
